ensure that submodule bumps are reachable
It occurs sometimes that a submodule is bumped to a PR commit instead of
the corresponding canonical branch (as registered in `.gitmodules`).
Because we typically use `squash`, that PR commit can subsequently
become unreachable, randomly breaking the build of `nimbus-eth2`.
Prevent these accidents by only allowing submodule bumps to commits
on the branch registered in `.gitmodules`. On private branches, simply
update `.gitmodules` to match the personal dev branch.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -82,6 +82,33 @@ jobs:
             exit 2
           fi
 
+      - name: Check submouldes (Linux)
+        if: github.event_name == 'pull_request' && runner.os == 'Linux'
+        run: |
+          while IFS='' read -r line; do
+            if [[ "${line:0:1}" == ' ' ]]; then
+              # No changes, skip
+              continue
+            fi
+
+            commit="${line:1:40}"
+            path="$(cut -f 1 -d ' ' <<<${line:42})"
+
+            if ! branch="$(git config -f .gitmodules --get submodule.$path.branch)"; then
+              echo "Submodule '$path': '.gitmodules' lacks 'branch' entry"
+              exit 2
+            fi
+
+            if ! error="$(git -C "$path" fetch -q origin "$branch")"; then
+              echo "Submodule '$path': Failed to fetch '$branch': $error"
+              exit 2
+            fi
+            if ! git -C "$path" merge-base --is-ancestor "$commit" "origin/$branch"; then
+              echo "Submodule '$path': '$commit' is not on '$branch'"
+              exit 2
+            fi
+          done < <(git submodule status)
+
       - name: MSYS2 (Windows amd64)
         if: runner.os == 'Windows' && matrix.target.cpu == 'amd64'
         uses: msys2/setup-msys2@v2
