attempt to reduce GitHub Actions runner disk usage

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -146,6 +146,17 @@ jobs:
           fixturesHash=$(getHash status-im/nim-eth2-scenarios)
           echo "::set-output name=fixtures::${fixturesHash}"
 
+      - name: Build binaries (with trace logging enabled)
+        run: |
+          if [[ "${{ matrix.branch }}" == "version-1-6" ]]; then
+            # change to "|| true" to hide the CI failures in GitHub's UI (escape hatch if a blocker is detected in 1.6)
+            ${make_cmd} -j ${ncpu} V=1 NIM_COMMIT=${{ matrix.branch }} LOG_LEVEL=TRACE || false
+          else
+            ${make_cmd} -j ${ncpu} V=1 NIM_COMMIT=${{ matrix.branch }} LOG_LEVEL=TRACE
+          fi
+          # The Windows image runs out of disk space, so make some room
+          rm -rf build nimcache
+
       - name: Restore Ethereum Foundation fixtures from cache
         id: fixtures-cache
         uses: actions/cache@v2
@@ -158,17 +169,6 @@ jobs:
       - name: Get the Ethereum Foundation fixtures
         run: |
           scripts/setup_scenarios.sh fixturesCache
-
-      - name: Build binaries (with trace logging enabled)
-        run: |
-          if [[ "${{ matrix.branch }}" == "version-1-6" ]]; then
-            # change to "|| true" to hide the CI failures in GitHub's UI (escape hatch if a blocker is detected in 1.6)
-            ${make_cmd} -j ${ncpu} V=1 NIM_COMMIT=${{ matrix.branch }} LOG_LEVEL=TRACE || false
-          else
-            ${make_cmd} -j ${ncpu} V=1 NIM_COMMIT=${{ matrix.branch }} LOG_LEVEL=TRACE
-          fi
-          # The Windows image runs out of disk space, so make some room
-          rm -rf nimcache
 
       - name: Run tests
         run: |
