fix detection for committed changes vs uncommitted

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -166,38 +166,22 @@ jobs:
       - name: Check submodules (Linux)
         if: github.event_name == 'pull_request' && runner.os == 'Linux'
         run: |
-          while IFS='' read -r line; do
-            # Format:
-            # - +/-/U/space to indicate changes
-            # - 40 characters commit
-            # - space
-            # - path to submodule
-            # - space
-            # - (
-            # - ref
-            # - )
-
-            if [[ "${line:0:1}" == ' ' ]]; then
-              # No changes, skip
-              continue
-            fi
-
-            commit="${line:1:40}"
-            path="$(cut -f 1 -d ' ' <<<${line:42})"
-
-            if ! branch="$(git config -f .gitmodules --get "submodule.$path.branch")"; then
-              echo "Submodule '$path': '.gitmodules' lacks 'branch' entry"
+          while read -r file; do
+            commit="$(git -C "$file" rev-parse HEAD)"
+            if ! branch="$(git config -f .gitmodules --get "submodule.$file.branch")"; then
+              echo "Submodule '$file': '.gitmodules' lacks 'branch' entry"
               exit 2
             fi
-            if ! error="$(git -C "$path" fetch -q origin "$branch")"; then
-              echo "Submodule '$path': Failed to fetch '$branch': $error"
+            echo "git -C $file fetch -q origin $branch"
+            if ! error="$(git -C "$file" fetch -q origin "$branch")"; then
+              echo "Submodule '$file': Failed to fetch '$branch': $error"
               exit 2
             fi
-            if ! git -C "$path" merge-base --is-ancestor "$commit" "origin/$branch"; then
-              echo "Submodule '$path': '$commit' is not on '$branch'"
+            if ! git -C "$file" merge-base --is-ancestor "$commit" "origin/$branch"; then
+              echo "Submodule '$file': '$commit' is not on '$branch'"
               exit 2
             fi
-          done < <(git submodule status)
+          done < <(git diff --name-only --diff-filter=AM HEAD^2 HEAD | grep -f <(git config --file .gitmodules --get-regexp path | awk '{ print $2 }') || true)
 
       - name: Get latest fixtures commit hash
         id: fixtures_version
